version: '3.8'

services:
  backend-app:
    image: backend-app:1.0.0
    container_name: backend-app
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 4000:4000
    networks:
      - application-network
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - app-mongo
    restart: unless-stopped
  app-mongo:
    image: 'mongo:4.4'
    container_name: app-mongo
    env_file:
      - .env.dev
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

networks:
  application-network:

volumes:
  mongodb:
  mongodb_config: